### ISSUE TITLE
Εχω προβλημα με το κουμπι "πισω" στον Firefox 49.0.2

### ISSUE THREAD

**Issue by xorz57** [Zarkopafilis/grafeio-foithtwn#1]
Δεν με αφηνει να παω στη προηγουμενη σελιδα με τιποτα και ξαναφορτωνει το site.

**Comment by Zarkopafilis** [comment]
Στην προηγουμενη σελιδα αφού μπεις στο index.html ή αφού πατήσεις link σύνδεσμου μέσα από αυτό;

**Comment by xorz57** [comment]
Το πρωτο, Στην προηγουμενη σελιδα αφού μπεις στο index.html
Εγω προσωπικα πηγα στο project σου στο github και πατησα πανω στο link να μπω να δω πως ειναι και σε καποια φαση ηθελα να επιστρεψω στο project σου στο github και το πισω δεν δουλευε.

**Comment by Zarkopafilis** [comment]
Εχεις δικιο, κολλαει σε λουπα για να φορτωνει τη css. Δοκιμασε soceid.tk . Κανω Update το description

**Comment by xorz57** [comment]
it works now ! good job!
