### ISSUE TITLE
Αργο φορτωμα του CSS.

### ISSUE THREAD

**Issue by xorz57** [Zarkopafilis/grafeio-foithtwn#2]
Τσεκαρε μια αυτο το guide-οειδες
https://varvy.com/pagespeed/render-blocking-css.html

Οι ικανοτητες μου στο web development ειναι σχεδον μηδαμηνες γιαυτο δεν μπορω να προτεινω κατι πιο ουσιαστικο!

**Comment by Zarkopafilis** [comment]
@xorz57 Ετοιμο theme ειναι. Το μονο θεμα που υπαρχει στο φορτωμα ειναι οτι χρησιμοποιω htmlpreview του github. Ο 'Konstantinos Vlachos' αποφασισε να παρει πρωτοβουλια να το χοσταρει στο soceid.tk : εκει φορτωνει αμεσως. Μπορει να παρουμε και domain και να συνεχισουμε τις βελτιωσεις.
